#!/usr/bin/env bash
set -euo pipefail

case "$(uname -m)-$(uname -s)" in
  x86_64-Linux) sys=homeConfigurations.gen-x86_64-linux.activationPackage ;;
  aarch64-Linux) sys=homeConfigurations.gen-aarch64-linux.activationPackage ;;
  arm64-Darwin | aarch64-Darwin) sys=homeConfigurations.gen-aarch64-darwin.activationPackage ;;
  *) echo "unsupported system" >&2; exit 1 ;;
esac

nix run --experimental-features 'nix-command flakes' .#"$sys"
